language: minimal

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - ocaml
    - os: osx
      osx_image: xcode11.3
      addons:
        homebrew:
          packages:
            - ocaml
  allow_failures:
    - os: osx

git:
  depth: 5
  submodules: false

before_install:
  - export -f travis_nanoseconds travis_time_start travis_time_finish

script:
  - ./travis.sh
